version: '3'

services:
  mysql-container:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: kaung
      MYSQL_PASSWORD: kaung
    ports:
      - "3307:3306"  # Change the host port to 3307
